spring:
  rabbitmq:
    host: localhost
    username: analytics_service
    password: password
    port: 5672

rabbitmq:
  exchange:
    scheduled-tasks-exchange: scheduled-tasks-exchange
  routing-keys:
    analytics-builder: analytics-builder-task
    vacancy-import: vacancy-import-task
  queue-names:
    analytics-builder: analytics-builder-scheduled-tasks-queue
    vacancy-import: vacancy-import-scheduled-tasks-queue
